In [1]:
class Character:
    
    def __init__(self):
        self.health = 200
        
    def move(self):
        self.health -= 10
        
    def rest(self):
        self.health += 10
        
    def attacked(self):
        self.health -= 30
        
    def checkHealth(self):
        print("Health : ", self.health)

In [11]:
class Knight(Character):
    
    def move(self):
        self.health -= 15
        
    def attack(self, character):
        print("공격합니다")
        character.attacked()

In [3]:
class Healer(Character):
    def __init__(self):
        super().__init__()
        self.mana = 100
        
    def heal(self, character):
        self.mana -= 10
        character.rest()
        
    
    def checkMana(self):
        print("현재 mana : ", self.mana)
        

In [4]:
knight_1 = Knight()

In [5]:
knight_1.move()
knight_1.checkHealth()

Health :  185


In [6]:
healer_1 = Healer()
healer_1.checkHealth()

Health :  200


In [7]:
knight_2 = Knight()
knight_2.move()
knight_2.move()
knight_2.checkHealth()

Health :  170


In [8]:
person = Character()
person.move()
person.move()
person.checkHealth()

Health :  180


In [9]:
healer_1.checkMana()
knight_1.checkHealth()
healer_1.heal(knight_1)
healer_1.checkMana()
knight_1.checkHealth()

현재 mana :  100
Health :  185
현재 mana :  90
Health :  195


In [12]:
person.checkHealth()
knight_1.attack(person)
person.checkHealth()

Health :  150
공격합니다
Health :  120


In [16]:
import numpy as np
a = np.array([[[1, 2, 3,3], [2, 3, 4, 5], [1,2,3, 6]], [[1, 2, 3,3], [2, 3, 4,5], [1,2,3, 6]]])

In [17]:
a.shape

(2, 3, 4)

In [20]:
x = np.linspace(1, 20)
x

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [19]:
np.linspace?

In [22]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
a = x.reshape(2, -1, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
print(x[1:3])

[1 2]


In [28]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
print(x[1:3])

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [30]:
print(x[1:3, 1:3])

[[ 6  7]
 [11 12]]


In [31]:
print(x[1:3, 1])

[ 6 11]


In [32]:
print(x[1:3, 1:2])

[[ 6]
 [11]]


In [33]:
x = np.arange(30).reshape(2,5,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [34]:
print(x[:, 3:5, 1])

[[10 13]
 [25 28]]


In [36]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
print(a[1][1])

6


In [38]:
print(a[1,1])

6


In [39]:
print(a[[1,1],[1,2]])

[6 7]


In [40]:
print(a > 3)

[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [41]:
print(a[a > 3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [42]:
print(a[a == 1])

[1]


In [43]:
print(a[~(a == 1)])

[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [44]:
print(a[a != 1])

[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [46]:
print(a[(a > 3) & (a < 8)])

[4 5 6 7]


In [47]:
print(a > 3)

[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [48]:
print(a < 8)

[[ True  True  True  True  True]
 [ True  True  True False False]
 [False False False False False]
 [False False False False False]]


In [49]:
a = 13
b =  9
a & b

9

In [50]:
np.random.rand(5, 5)

array([[0.56076156, 0.33029712, 0.99688174, 0.71789885, 0.84750384],
       [0.55844251, 0.05283948, 0.22664323, 0.0518793 , 0.4432652 ],
       [0.40863803, 0.41464434, 0.2135517 , 0.34043207, 0.80367887],
       [0.48793199, 0.59644983, 0.39104521, 0.38456997, 0.86317292],
       [0.44056709, 0.69738676, 0.01085178, 0.60890563, 0.30812503]])

In [61]:
np.random.randint(1, 10)

2

In [62]:
np.random.randint(1, 10, size=(5))

array([5, 9, 7, 2, 4])

In [66]:
x =np.random.randint(1, 10, size=(5,3))
x

array([[5, 2, 3],
       [2, 7, 1],
       [1, 3, 3],
       [9, 3, 1],
       [1, 2, 9]])

In [67]:
x.ravel()

array([5, 2, 3, 2, 7, 1, 1, 3, 3, 9, 3, 1, 1, 2, 9])

In [68]:
x.ravel(order="C")

array([5, 2, 3, 2, 7, 1, 1, 3, 3, 9, 3, 1, 1, 2, 9])

In [69]:
x.ravel(order="F")

array([5, 2, 1, 9, 1, 2, 7, 3, 3, 2, 3, 1, 3, 1, 9])

In [70]:
np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
x = np.arange(1, 4)
x

array([1, 2, 3])

In [74]:
y = np.arange(4, 7)
y

array([4, 5, 6])

In [76]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [77]:
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
y = np.arange(10, 20).reshape(2, 5)
y

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [79]:
np.concatenate([x, y])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [80]:
np.concatenate([x, y], axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [81]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
a = np.split(x, 4)
a
type(a[0])

numpy.ndarray

In [85]:
x = np.arange(16).reshape(4, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
np.split(x, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [87]:
np.split(x, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

array([3, 6, 1, 9, 2])

In [91]:
x = np.array([1, 2, 3])
x + 1

array([2, 3, 4])

In [92]:
x = np.arange(1, 10).reshape(3, 3)
y = np.arange(1, 4)
x + y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [93]:
x = np.array([10, 20, 30]).reshape(3, 1)
y = np.arange(1, 4)
print(x)
print()
print(y)

[[10]
 [20]
 [30]]

[1 2 3]


In [94]:
x + y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [97]:
x = np.arange(4).reshape(2,2)
y = np.arange(4, 8).reshape(2,2)

x.dot(y)

array([[ 6,  7],
       [26, 31]])

In [98]:
x*y

array([[ 0,  5],
       [12, 21]])

In [99]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [102]:
inv_x = np.linalg.inv(x)
inv_x

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [103]:
x.dot(inv_x)

array([[1., 0.],
       [0., 1.]])

In [104]:
np.linalg.det(x)

-2.0

In [105]:
np.mean(x)

1.5

In [106]:
a = np.array([10, 3, -5, 2, 7])
np.median(a)

3.0

In [108]:
a = np.array([10, 3, -5, 2, 7, 4])
np.median(a)

3.5

In [109]:
np.mean(a)

3.5

In [111]:
np.var(a)

21.583333333333332

In [112]:
np.var(x)

1.25

In [113]:
np.std(a)

4.645786621588784

In [114]:
np.std(x)

1.118033988749895

In [115]:
np.sum(a)

21

In [116]:
np.sum(x)

6

In [117]:
x

array([[0, 1],
       [2, 3]])

In [118]:
np.sum(x, axis=1)

array([1, 5])

In [119]:
np.sum(x, axis=0)

array([2, 4])

In [120]:
np.cumsum(x)

array([0, 1, 3, 6], dtype=int32)

In [121]:
np.cumprod(x)

array([0, 0, 0, 0], dtype=int32)

In [122]:
np.min(a)

-5

In [123]:
np.max(a)

10

In [124]:
np.argmax(a)

0

In [125]:
a

array([10,  3, -5,  2,  7,  4])

In [126]:
np.argmin(a)

2

In [127]:
np.any(a > 4)

True

In [128]:
np.all(a > 4)

False

In [129]:
np.where(a > 4)

(array([0, 4], dtype=int64),)

In [130]:
a

array([10,  3, -5,  2,  7,  4])

In [134]:
np.where(a > 4, a, 0)

array([10,  0,  0,  0,  7,  0])

In [135]:
x = np.arange(30).reshape(2,5,3)

In [136]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [139]:
print(x[1:3, 3])

[ 8 13]


In [140]:
x = np.arange(30).reshape(2,5,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [142]:
(x[:, 3:5, 1]).shape

(2, 2)

In [144]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [145]:
np.where(a > 4)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [146]:
import pandas as pd

In [147]:
x = [1, 2, 3, 4, 5]
s = pd.Series(x)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [149]:
print(s.index)

RangeIndex(start=0, stop=5, step=1)


In [151]:
s.values

array([1, 2, 3, 4, 5], dtype=int64)

In [152]:
type(s.values)

numpy.ndarray

In [153]:
s = pd.Series(x, index=['a', 'b', 'c', 'd', 'e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [154]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [155]:
s['c']

3

In [156]:
s[2]

3

In [158]:
s[['b', 'd']]

b    2
d    4
dtype: int64

In [159]:
s[[0, 3]]

a    1
d    4
dtype: int64

In [160]:
s.a

1

In [161]:
x = {"수학":90, "영어":80, "과학":95, "미술":80}
x = pd.Series(x)
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [162]:
x.index

Index(['수학', '영어', '과학', '미술'], dtype='object')

In [163]:
x['수학']

90

In [168]:
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [170]:
part = pd.Series(x, index=["수학", "영어", "과학"])

In [171]:
part

수학    90
영어    80
과학    95
dtype: int64

In [172]:
student_1 = {"수학":90, "영어":80, "과학":95, "미술":80}
student_2 = {"수학":70, "영어":90, "과학":100, "미술":70}

In [180]:
index_1 = ["홍길동" for i in  range(len(student_1))] + ["이몽룡" for i in  range(len(student_2))]

In [177]:
index_2 = list(student_1.keys()) + list(student_2.keys())
index_2

['수학', '영어', '과학', '미술', '수학', '영어', '과학', '미술']

In [178]:
value_all = list(student_1.values()) + list(student_2.values())
value_all

[90, 80, 95, 80, 70, 90, 100, 70]

In [181]:
students = pd.Series(value_all, index=[index_1, index_2])
students

홍길동  수학     90
     영어     80
     과학     95
     미술     80
이몽룡  수학     70
     영어     90
     과학    100
     미술     70
dtype: int64

In [186]:
students['수학']

KeyError: '수학'

In [203]:
x = [1, None, 2, None, 3, 4, None]
x = pd.Series(x)
x

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
5    4.0
6    NaN
dtype: float64

In [188]:
print(x.sum())

10.0


In [189]:
print(x.max())
print(x.min())

4.0
1.0


In [191]:
print(x.isnull().sum())

3


In [192]:
print(x.notnull().sum())

4


In [193]:
x.dropna()

0    1.0
2    2.0
4    3.0
5    4.0
dtype: float64

In [204]:
x.dropna(inplace=True)


In [205]:
x

0    1.0
2    2.0
4    3.0
5    4.0
dtype: float64

In [195]:
x.fillna(0)

0    1.0
1    0.0
2    2.0
3    0.0
4    3.0
5    4.0
6    0.0
dtype: float64

In [196]:
x

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
5    4.0
6    NaN
dtype: float64

In [206]:
x = pd.Series([1, 2, 3])
y = pd.Series([4, 5, 6])
z = pd.Series([7, 8, 9])


In [207]:
pd.concat([x, y, z])

0    1
1    2
2    3
0    4
1    5
2    6
0    7
1    8
2    9
dtype: int64

In [199]:
pd.concat([x, y, z], verify_integrity=True)

ValueError: Indexes have overlapping values: Int64Index([0, 1, 2], dtype='int64')

In [200]:
pd.concat([x, y, z], ignore_index=True)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [209]:
type(pd.concat([x, y, z], ignore_index=True, axis=1))

pandas.core.frame.DataFrame

In [213]:
x = pd.Series([1, 2, 3, 4])
y = pd.Series([4, 5, 6])
z = pd.Series([7, 8, 9])


In [214]:
pd.concat([x, y, z], ignore_index=True, axis=1, join='outer')

0    1    2
0  1  4.0  7.0
1  2  5.0  8.0
2  3  6.0  9.0
3  4  NaN  NaN

In [216]:
x = pd.Series([1, 2, 3, 4, 5])
y = pd.Series([6, 7, 8, 9, 0])


In [217]:
print(x.add(10))
print(x.add(y))


0    11
1    12
2    13
3    14
4    15
dtype: int64
0     7
1     9
2    11
3    13
4     5
dtype: int64


In [218]:
print(x.mul(y))

0     6
1    14
2    24
3    36
4     0
dtype: int64


In [219]:
print(x.mod(2)) # x[i] % 2 

0    1
1    0
2    1
3    0
4    1
dtype: int64


In [220]:
x.count()

5

In [221]:
print(x.min())
print(x.max())
print(x.mean())
print(x.median())


1
5
3.0
3.0


In [222]:
x.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [223]:
x

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [224]:
x.head(2)

0    1
1    2
dtype: int64

In [225]:
x.tail(2)

3    4
4    5
dtype: int64