In [5]:
def func1():
    def func2():
        print("school")
    func2()

func1()



school


In [19]:
class Dog:
    def __init__(self, name, color):
        self.hungry = 0
        self.name = name
        self.color = color
        
    def eat(self):
        self.hungry -= 10
        print("밥먹음", self.hungry)
    def walk(self):
        self.hungry += 10
        print("산책", self.hungry)
    def showme(self):
        print(f"{self.name} : {self.color}")

In [21]:
choco = Dog("choco", "black")
choco.eat()
choco.eat()
choco.walk()
choco.showme()

밥먹음 -10
밥먹음 -20
산책 -10
choco : black


In [23]:
jjong = Dog("jjong", "white")
print(jjong.hungry)
jjong.hungry = 10
print(jjong.hungry)


0
10


In [20]:
choco.eat()

eat


In [45]:
class Dog:
    def __init__(self, name, color):
        self.__hungry = 0
        self.name = name
        self.color = color
        
    def eat(self):
        self.__hungry -= 10
        self.bark ="walwal"
        print("밥먹음", self.__hungry, bark)
        
    def walk(self):
        self.__hungry += 10
        print("산책", self.__hungry, self.bark)
        
    def showme(self):
        print(f"{self.name} : {self.color}")

In [46]:
mery = Dog("mery", "black")
mery.eat()
mery.walk()
mery.walk()

NameError: name 'bark' is not defined

In [44]:
print(mery.bark)


AttributeError: 'Dog' object has no attribute 'bark'

In [31]:
print(mery._hungry)

200


In [1]:
class Dog:
    dog_count = 0
    
    def __init__(self, name, color):
        self.name = name
        self.color = color
        self.dog_count = 0
        Dog.dog_count += 1
    
    def dogCount(self):
        self.dog_count += 1
        print("총 강아지는 ", Dog.dog_count)
        print("내 강아지는 ", self.dog_count)

In [2]:
hello = Dog("hello", "black")
hello.dogCount()

총 강아지는  1
내 강아지는  1


In [3]:
happy = Dog("happy", "black")
happy.dogCount()

총 강아지는  2
내 강아지는  1


In [75]:
class Car:
    carCount = 0
    
    def __init__(self, name, volume, year):
        self.__name = name
        self.__volume = volume
        self.__year = year
        Car.carCount += 1
    
    def get_name(self):
        print("차종은 {}입니다".format(self.__name))
        
    def change_name(self, new_name):
        self.__name = new_name
        
    def show_volume(self):
        if self.__volume < 1000:
            print("소형")
        elif self.__volume <= 2000:
            print("중형")
        else:
            print("대형")
    
    @classmethod
    def get_total_cars(cls):
        print("총 등록된 차량개수 : ", Car.carCount)

In [76]:
hyundai = Car("i30", 1800, 2000)
benz = Car("benz", 3000, 2015)
kia = Car("morning", 900, 2020)

In [77]:
hyundai.get_name()

차종은 i30입니다


In [78]:
hyundai.change_name("펠리세이드")
hyundai.get_name()

차종은 펠리세이드입니다


In [79]:
Car.get_total_cars()

총 등록된 차량개수 :  3


In [84]:
class Animal:
    def __init__(self):
        self.hungry = 0
        
    def eat(self):
        self.hungry -= 10
        print("밥먹음", self.hungry)
    
    def walk(self):
        self.hungry += 10
        print("산책", self.hungry)

In [85]:
class Dog(Animal):
    def __init__(self):
        super().__init__()
        
    def sound(self):
        print("멍멍")

In [86]:
class Cat(Animal):
    def __init__(self):
        super().__init__()
        
    def sound(self):
        print("야옹")

In [87]:
dog = Dog()
dog.sound()

멍멍


In [88]:
dog.walk()

산책 10


In [89]:
cat = Cat()

In [90]:
cat.sound()

야옹


In [91]:
cat.eat()

밥먹음 -10


In [96]:
class Dog(Animal):
    def __init__(self):
        super().__init__()
        
    def sound(self):
        print("멍멍")
        
    def eat(self):
        if type == "밥":
            print("멍멍")
        else:
            print("왈왈")
        

In [97]:
dog = Dog()
dog.eat("밥")

멍멍


In [99]:
dog.eat()

TypeError: eat() missing 1 required positional argument: 'type'

In [100]:
animal = Animal()

In [101]:
animal.eat()

밥먹음 -10


In [105]:
for i in range(10, -10, -1):
    try:
        print(10/i)
    except ZeroDivisionError as e:
        print("에러가 발생했습니다", e)

1.0
1.1111111111111112
1.25
1.4285714285714286
1.6666666666666667
2.0
2.5
3.3333333333333335
5.0
10.0
에러가 발생했습니다 division by zero
-10.0
-5.0
-3.3333333333333335
-2.5
-2.0
-1.6666666666666667
-1.4285714285714286
-1.25
-1.1111111111111112


In [1]:
x = [1, 2, 3, 4]


a = x[4]


IndexError: list index out of range

In [113]:
class NotNumber(Exception):
    def __init__(self):
        super().__init__("잘못된 숫자입니다")


In [114]:
def gugudan(num):
    if num < 1 or num > 9:
        #error raise
        raise NotNumber
        
    for i in range(1, 10):
        print(f"{num} * {i} = {num * i}")

In [121]:
try:
    gugudan(10)
except NotNumber as e:
    print("error : 1~9 사이 숫자를 넣어주세요")

error : 1~9 사이 숫자를 넣어주세요


In [125]:
import pickle

try:
    with open("data3.pkl", "rb") as file:
        name = pickle.load(file)
        address = pickle.load(file)
        email = pickle.load(file)
        print(name, address, email)
        
except FileNotFoundError as e:
    print("file이 존재하지 않습니다")
    name = input("이름을 입력해주세요")
    address = input("주소를 입력해주세요")
    email = input("이메일을 입력해주세요")
    
    with open("data3.pkl", "wb") as file:
        pickle.dump(name, file)
        pickle.dump(address, file)
        pickle.dump(email, file)
    
    print("파일이 생성되었습니다.")
    

홍경수 강석로 152 ronen@fins.ai


In [3]:
import pkcalc.calc as calc

print(calc.name)

calc


In [128]:
from calc import add

print(add(5, 6))

11


In [6]:
from pkcalc.calc import add, sub 

calc package


In [2]:
import sys
print(sys.path)


['C:\\Users\\690\\kdigital', 'C:\\Users\\690\\anaconda3\\python38.zip', 'C:\\Users\\690\\anaconda3\\DLLs', 'C:\\Users\\690\\anaconda3\\lib', 'C:\\Users\\690\\anaconda3', '', 'C:\\Users\\690\\anaconda3\\lib\\site-packages', 'C:\\Users\\690\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\690\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\690\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\690\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\690\\.ipython']


In [3]:
sys.path.append("C:\\Users\\690")

In [4]:

print(sys.path)

['C:\\Users\\690\\kdigital', 'C:\\Users\\690\\anaconda3\\python38.zip', 'C:\\Users\\690\\anaconda3\\DLLs', 'C:\\Users\\690\\anaconda3\\lib', 'C:\\Users\\690\\anaconda3', '', 'C:\\Users\\690\\anaconda3\\lib\\site-packages', 'C:\\Users\\690\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\690\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\690\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\690\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\690\\.ipython', 'C:\\Users\\690']


In [5]:
import pkcalc 

calc package


In [3]:
print(pkcalc.add(5, 6))

11


In [5]:
from pkcalc.calc import add, sub 
print(add(5,6))

11


In [4]:
!python pkcalc/calc.py

14


In [6]:
import numpy as np

In [7]:
import pandas as pd

In [19]:
matrix_1 = [[1, 2], [3, 4]]
matrix_2 = [[5, 6], [7, 8]]

In [9]:
def matrix_sum (mat_1, mat_2):
    for i in range(len(matrix_1)):
        for j in range(len(matrix_1[0])):
            mat_1[i][j] += mat_2[i][j]
            
    return mat_1

In [11]:
#matrix 원소의 합 =>[[6, 8], [10, 12]]
matrix_sum(matrix_1, matrix_2)
print(matrix_1)

[[6, 8], [10, 12]]


In [17]:
#matrix_1 의 원소에 1 더하기 => [[2, 3], [4, 5]]
def mat_add_one(mat):
    for i in range(len(mat)):
        for j in range(len(mat[0])):
            mat[i][j] += 1

In [18]:
mat_add_one(matrix_1)
matrix_1

[[2, 3], [4, 5]]

In [20]:
mat_sum = np.array(matrix_1) + np.array(matrix_2)
print(mat_sum)

[[ 6  8]
 [10 12]]


In [23]:
mat_one_plus = np.array(matrix_1)  + 1
mat_one_plus

array([[2, 3],
       [4, 5]])

In [26]:
import time

size = 10000000

x = list(range(size))
y = list(range(size))




In [25]:
print(time.localtime())

time.struct_time(tm_year=2020, tm_mon=12, tm_mday=15, tm_hour=17, tm_min=21, tm_sec=35, tm_wday=1, tm_yday=350, tm_isdst=0)


In [27]:
start_time = time.time()
z = [ x[i] + y[i] for i in range(size)]
print(f"리스트 걸릴 시간 : {time.time() - start_time }")

리스트 걸릴 시간 : 2.116347551345825


In [30]:
x = np.arange(size)
y = np.arange(size)

In [31]:
start_time = time.time()
z = x + y 
print(f"넘파이 걸릴 시간 : {time.time() - start_time }")

넘파이 걸릴 시간 : 0.19798898696899414


In [39]:
x = np.uint(64)
print(x)
print(type(x))
print(x.dtype)

64
<class 'numpy.uint32'>
uint32


In [40]:
x = np.array([1,2,3,4])
print(x)
print(type(x))
print(x.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int32


In [41]:
x = np.float32([1, 2, 3, 4])
print(x)
print(type(x))
print(x.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float32


In [43]:
x = np.array([1,2,3,4], dtype=np.float16)
print(x)
print(type(x))
print(x.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float16


In [46]:
x = np.int32(x)
print(x.dtype)
print(x)

int32
[1 2 3 4]


In [48]:
np.issubdtype(x.dtype, np.int32)

True

In [57]:
x = np.array([1,2])

In [50]:
print(x.shape)

(2,)


In [51]:
print(x)

[1 2]


In [66]:
x = np.array([[[[1, 2, 3], [4, 5,6], [1, 2, 3]]]])
print(x.ndim)

4


In [67]:
print(x.shape)

(1, 1, 3, 3)


In [69]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [70]:
x = x.reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [71]:
x = np.arange(24).reshape(2, 3, 4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [72]:
print(x.shape)

(2, 3, 4)


In [73]:
x = np.array([[1,2],[3,4],[5,6]])

In [74]:
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [75]:
print(x.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


In [78]:
x  = np.arange(9).reshape(3, -1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [79]:
x = np.arange(24).reshape(2, 3, 4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [81]:
print(x.reshape(4, 2, -1))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
