## Tensorflow 기초

In [1]:
import tensorflow as tf

print("tf ver =", tf.__version__ )

tf ver = 2.1.0


In [7]:
#tensorflow(1.x ver)
x = tf.constant(1)
y = tf.constant(2)
z = tf.constant(3)

a = x*y+z

Sess = tf.Session()
b = sess.run(a)

AttributeError: module 'tensorflow' has no attribute 'Session'

In [8]:
#tensorflow(2.x ver)
x = tf.constant(1)
y = tf.constant(2)
z = tf.constant(3)

a = x*y+z

print(a)

tf.Tensor(5, shape=(), dtype=int32)


1. tf 1.X 환경을 만들어서 실행..
    -. virenv
2. tf 2.x 환경에서 1.x를 실행할수 있게

In [9]:
# import tensorflow.compat.v1 as tf
# tf.disable_v2_behavior()
#tensorflow(1.x ver)
x = tf.constant(1)
y = tf.constant(2)
z = tf.constant(3)

a = x*y+z

sess = tf.Session()
b = sess.run(a)
print(b)

Instructions for updating:
non-resource variables are not supported in the long term
5


In [2]:
a = tf.constant([[1,2],[3,4],[5,6],
                 [7,8],[9,10],[11,12]])

print(a)

tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]], shape=(6, 2), dtype=int32)


In [3]:
a = tf.constant([[1.,2],[3,4],[5,6],
                 [7,8],[9,10],[11,12]])

print(a)

tf.Tensor(
[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]
 [11. 12.]], shape=(6, 2), dtype=float32)


In [4]:
tf.reshape(a,[3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)>

In [5]:
b = tf.reshape(a,[-1,6])
b

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]], dtype=float32)>

In [6]:
tf.transpose(b) # 전치행렬

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[ 1.,  7.],
       [ 2.,  8.],
       [ 3.,  9.],
       [ 4., 10.],
       [ 5., 11.],
       [ 6., 12.]], dtype=float32)>

In [7]:
a = tf.constant([1,2,3,4,5])
b = tf.constant([-1,-1,-1,-1,-1])
c= a*b
print(c)

tf.Tensor([-1 -2 -3 -4 -5], shape=(5,), dtype=int32)


In [11]:
a_data = [1,2,3,4,5]
b_data = [-1,-1,-1,-1,-1]
a = tf.constant(a_data)
b = tf.constant(b_data)
c= a*b
print(c)

tf.Tensor([-1 -2 -3 -4 -5], shape=(5,), dtype=int32)


In [8]:
c.numpy()

array([-1, -2, -3, -4, -5])

In [9]:
a = tf.constant([1,2,3,4,5])
b = tf.constant([1,4,6,4,9])
c = tf.equal(a,b) # 2개의 벡터 원소 간 비교
print(c)

tf.Tensor([ True False False  True False], shape=(5,), dtype=bool)
