In [1]:
import pandas as pd
#수정 필요
# url ="https://docs.google.com/spreadsheets/d/1fiioUPMRurfE523yWGaRF3ckO-TUHu1AaIAI6Eo7Ti8/edit#gid=1592374929"

In [3]:
df = pd.read_csv("titles - titles.csv")
df

title  year
0                The Rising Son  1990
1             Ashes of Kukulcan  2016
2       The Thousand Plane Raid  1969
3              Crucea de piatra  1993
4                        The 86  2015
...                         ...   ...
215976           Le mouton noir  1922
215977      Edge of the Unknown  2015
215978                    E yue  2005
215979             Lakota Girls  2015
215980             The Sting II  1983

[215981 rows x 2 columns]

1. pd 기본
    - pd.head(가져올 개수)
    - pd.shape # 모양
    - pd.columns
    - pd.info # 정보
    - pd.describe # value에 대한 값 (숫자에 대한 것만 )
    - pd.isnull.sum() #결측값 

In [5]:
df.shape

(215981, 2)

In [7]:
df.head(3)

title  year
0           The Rising Son  1990
1        Ashes of Kukulcan  2016
2  The Thousand Plane Raid  1969

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215981 entries, 0 to 215980
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   title   215981 non-null  object
 1   year    215981 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 3.3+ MB


In [9]:
df.info

<bound method DataFrame.info of                           title  year
0                The Rising Son  1990
1             Ashes of Kukulcan  2016
2       The Thousand Plane Raid  1969
3              Crucea de piatra  1993
4                        The 86  2015
...                         ...   ...
215976           Le mouton noir  1922
215977      Edge of the Unknown  2015
215978                    E yue  2005
215979             Lakota Girls  2015
215980             The Sting II  1983

[215981 rows x 2 columns]>

In [14]:
df.tail(3)

title  year
215978         E yue  2005
215979  Lakota Girls  2015
215980  The Sting II  1983

In [13]:
df.isnull().sum()

title    0
year     0
dtype: int64

In [16]:
df.describe()

year
count  215981.000000
mean     1984.553822
std        29.343957
min      1894.000000
25%      1965.000000
50%      1994.000000
75%      2010.000000
max      2024.000000

In [17]:
len(df)

215981

In [19]:
df.sort_values("year",ascending=False).head(2)

title  year
199790  New in Village  2024
44198        Wild Runs  2024

In [20]:
df.sort_values("year",ascending=True).head(2)

title  year
165182                                         Miss Jerry  1894
85708   Reproduction of the Corbett and Fitzsimmons Fight  1897

In [25]:
df[df["title"]=="Hamlet"]

title  year
5562    Hamlet  1948
26160   Hamlet  2016
37373   Hamlet  2015
42224   Hamlet  1990
43511   Hamlet  1910
68239   Hamlet  1954
85741   Hamlet  1976
87781   Hamlet  1987
87971   Hamlet  2000
91710   Hamlet  1921
114224  Hamlet  1969
154627  Hamlet  1913
163645  Hamlet  2009
169996  Hamlet  1964
186988  Hamlet  1996
192815  Hamlet  2011
195015  Hamlet  1911
205821  Hamlet  1973
207793  Hamlet  2014

In [24]:
df[df["title"]=="Hamlet"].shape

(19, 2)

In [28]:
df[df["title"] == "Treasure Island"].sort_values("year").head(10)

title  year
191379  Treasure Island  1918
47769   Treasure Island  1920
192917  Treasure Island  1934
90175   Treasure Island  1950
104714  Treasure Island  1972
103646  Treasure Island  1973
190792  Treasure Island  1985
166675  Treasure Island  1999

In [ ]:
# df[(df["year"] >= 1950)] and df[(df["year"] <= 1959)]

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
# x = [[1,2,3,0],
#      [11,12,13,1]]
# 기존 데이터 독립변수와 종속변수 한번에 표현

In [33]:
clf = RandomForestClassifier(random_state=0)
x = [[1,2,3],
     [11,12,13],
    [23,33,45]] # 독립변수

y = [0,1,0] # 종속변수

clf.fit(x,y)

RandomForestClassifier(random_state=0)

In [34]:
clf.predict(x) # 예측값 행의 갯수 만큼 나온다

array([0, 1, 0])

In [35]:
clf.predict([[234,23,456]])

array([0])

In [36]:
clf.predict([[234,23,456],[12,55,777]])

array([0, 0])

In [37]:
clf.predict([234,23,456]) # 차원을 맞춰야한다.(1차원은 1차원 2차원은 2차원)

ValueError: Expected 2D array, got 1D array instead:
array=[234.  23. 456.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [41]:
import numpy as np

rs = np.random.RandomState(10) # Seed값 고정, 난수의Seed값
x = 10 * rs.rand(5) # 난수 5개 생성
y = 2 * x - 1 * rs.rand(5) # y절편을 바꾸기 위해서 rs.rand(5)를 곱한다.
#                             (절편이 다른 다양한 그래프를 볼 수 있음)
x.shape, y.shape

((5,), (5,))

In [42]:
X=x.reshape(-1,1) #행렬의 형태를 변화시키기 위해 (행 또는 열을 정하고 마지막 하나의 행 또는 열을 
#                   -1로 지정할 경우 행렬이 자동으로 정리된다.)
X.shape

(5, 1)