In [6]:
class Character:
    def __inti__(self):
        self.health = 200
    
    def move(self):
        self.health -= 10
        
    def rest(self):
        self.health += 10
        
    def checkHealth(self):
        print("Health:" .self.health)

In [2]:
class Knight(Character):
    
    def __init__(self):
        super(). __init__(self)
    
    def move(self):
        self.health -= 15
    
    def attack(self):
        print("공격합니다")

In [10]:
knight_1 = Knight()


In [20]:
class Healer(Character):
    
    def __init__(self):
        self.mana = 100
        
    def heal(self):
        self.mana -= 10
        character.rest()
        
    def checkMana(self):
        print("현재 mana:".self.mana)

In [21]:
healer_1 = Healer()
healer_1.checkHealth()

AttributeError: 'str' object has no attribute 'self'

In [22]:
knight_2 = Knight()
knight_2. attack()
knight_2. attack()
knight_2.checkHealth()

공격합니다
공격합니다


AttributeError: 'Knight' object has no attribute 'checkHealth'

In [23]:
person = Chatacter()
person.move()
person.move()
person.checkHealth()

NameError: name 'Chatacter' is not defined

In [24]:
healer_1.checkMana()
knight_1.checkHealth()
healer_1.healer

AttributeError: 'str' object has no attribute 'self'

In [29]:
import numpy as np
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [31]:
print(x[1:3])

[1 2]


In [33]:
a = np.arange(20).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [35]:
print(a[1:3])

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [39]:
print(a[1:3, 1:3])

[[ 6  7]
 [11 12]]


In [40]:
print(a[1:3, 1])

[ 6 11]


In [48]:
print(a[0 ,1:3])

[1 2]


In [50]:
c = np.arange(12)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [51]:
c = np.arange(12).reshape(3,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [57]:
c = np.arange(12).reshape(12,1)
print(c)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [53]:
c = np.arange(12).reshape(2,6)
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [54]:
c = np.arange(12).reshape(2,2,3)
print(c)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [55]:
c = np.arange(12).reshape(3,2,2)
print(c)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [56]:
c = np.arange(12).reshape(4,3)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [59]:
c = np.arange(24).reshape(3,2,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [60]:
c = np.arange(24).reshape(3,4,2)
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [63]:
np.random.rand(5,5)

array([[0.71935655, 0.85222124, 0.1968016 , 0.89417961, 0.88568954],
       [0.44503148, 0.37464286, 0.9254978 , 0.28309821, 0.19157982],
       [0.19044402, 0.27334626, 0.71569034, 0.53069136, 0.8238068 ],
       [0.98217093, 0.7647543 , 0.37856862, 0.27722149, 0.4281797 ],
       [0.63538838, 0.31077909, 0.28960092, 0.40098615, 0.8379418 ]])

In [87]:
np.random.randint(1,10)

4

In [94]:
np.random.randint(1,10,size=(5))

array([6, 6, 1, 7, 6])

In [111]:
np.random.randint(1,10,size=(5,5))

array([[7, 9, 4, 7, 6],
       [2, 1, 5, 8, 2],
       [4, 9, 9, 1, 1],
       [4, 4, 8, 8, 4],
       [5, 4, 5, 8, 1]])

In [146]:
np.random.rand(5)

array([0.67842398, 0.19475346, 0.43207672, 0.72696954, 0.62796625])

In [147]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [148]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [150]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [153]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [155]:
y = np.arange(1,4)
y

array([1, 2, 3])

NameError: name 'array' is not defined

In [161]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [162]:
np.split(x, 4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [169]:
x = np.arange(16).reshape(8,2)
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [170]:
np.split(x,2)

[array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]),
 array([[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]])]

In [171]:
np.split(x,4)

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[ 8,  9],
        [10, 11]]),
 array([[12, 13],
        [14, 15]])]

In [172]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [173]:
np.split(x,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [174]:
np.split(x, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [175]:
x = np.arange(16).reshape(8,2)
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [177]:
np.split(x, 2, axis=1)

[array([[ 0],
        [ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12],
        [14]]),
 array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15]])]

In [178]:
np.split(x, 4, axis=1)

ValueError: array split does not result in an equal division

In [179]:
y = np.arange(16).reshape(4,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [180]:
np.split(y,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [181]:
np.split(y,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [182]:
np.split(y,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [183]:
np.split(y,4,axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [184]:
x = np.arange(16).reshape(2,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [185]:
np.split(x,4,axis=1)

[array([[0, 1],
        [8, 9]]),
 array([[ 2,  3],
        [10, 11]]),
 array([[ 4,  5],
        [12, 13]]),
 array([[ 6,  7],
        [14, 15]])]

In [189]:
q = np.array([1,2,3])
q+1

array([2, 3, 4])

In [190]:
x = np.arange(1,10).reshape(3,3)
y=np.arange(1,4)
x+y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [202]:
x = np.arange(4).reshape(2,2)
y = np.arange(4).reshape(2,2)

In [203]:
print(x)

[[0 1]
 [2 3]]


In [204]:
print(y)

[[0 1]
 [2 3]]


In [205]:
x.dot(y)

array([[ 2,  3],
       [ 6, 11]])

In [206]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [208]:
np.linalg.inv(x)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [210]:
np.linalg.det(x)

-2.0

In [213]:
a = np.arange(1,10).reshape(3,3)

In [214]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [215]:
np.mean(a)

5.0

In [223]:
np.median(a)

5.0

In [217]:
np.std(a)

2.581988897471611

In [218]:
np.sum(a)

45

In [224]:
np.var(a)

6.666666666666667

In [232]:
np.sum(a,axis=0)

array([12, 15, 18])

In [234]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [228]:
b = np.arange(8).reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [229]:
np.sum(b,axis=1)

array([ 6, 22])

In [241]:
np.sum(b,axis=0)

array([ 4,  6,  8, 10])

In [239]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [240]:
np.cumprod(a)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [237]:
np.int32

numpy.int32

In [242]:
np.min(a)

1

In [243]:
np.argmin(a)

0

In [244]:
np.argmax(a)

8

In [245]:
np.any(a>4)

True

In [246]:
np.all(a>4)

False

In [254]:
(np.where(a>4))

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [250]:
np.where(a>4,a,-100)

array([[-100, -100, -100],
       [-100,    5,    6],
       [   7,    8,    9]])

In [251]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [257]:
b = np.arange(1, 10).reshape(3, 3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [258]:
np.where(b > 3)

(array([1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [260]:
x = np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [262]:
np.where(x > 2)

(array([1, 1], dtype=int64), array([0, 1], dtype=int64))

In [263]:
import pandas as pd

In [265]:
x = [1,2,3,4,5]
s = pd.Series(x)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [266]:
print(s.index)

RangeIndex(start=0, stop=5, step=1)


In [267]:
s.values

array([1, 2, 3, 4, 5], dtype=int64)

In [268]:
type(s.values)

numpy.ndarray

TypeError: __init__() got an unexpected keyword argument 'idex'

In [282]:
x = {"수학":90,"영어":80,"과학":95,"미술":80}
x = pd.Series(x)
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [283]:
x.index

Index(['수학', '영어', '과학', '미술'], dtype='object')

In [284]:
x["수학"]

90

In [287]:
x["영어":"미술"]

영어    80
과학    95
미술    80
dtype: int64

In [288]:
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [289]:
part = pd.Series(x, index=["수학","영어","과학"])

In [290]:
part

수학    90
영어    80
과학    95
dtype: int64

In [292]:
student_1 = {"수학":90,"영어":80,"과학":95,"미술":80}
student_2 = {"수학":70,"영어":90,"과학":100,"미술":70}

In [298]:
index_1 = ["홍길동" for i in range(len(student_1))] + ["이몽룡" for i in range(len(student_2))]

In [299]:
index_2 = list(student_1.keys()) + list(student_2.keys())
index_2

['수학', '영어', '과학', '미술', '수학', '영어', '과학', '미술']

In [300]:
value_all = list(student_1.values()) + list(student_2.values())
value_all

[90, 80, 95, 80, 70, 90, 100, 70]

In [303]:
students = pd.Series(value_all, index=[index_1,index_2])
students

홍길동  수학     90
     영어     80
     과학     95
     미술     80
이몽룡  수학     70
     영어     90
     과학    100
     미술     70
dtype: int64

In [306]:
students["홍길동"]["수학"]

90

In [312]:
x = [1,2,3,4,5,6,7,8,9]

In [314]:
x = np.array(x).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [310]:
y = [10,20,30,40,50,60,70,80,90]

In [316]:
y = np.array(y).reshape(3,3)
y

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [317]:
x+y

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [318]:
x.dot(y)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [319]:
x = np.linspace(1,20,30)

In [320]:
x

array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

In [321]:
x+10

array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

In [325]:
#1~100까지난수가들어가있는#2x10x10배열을만들고# 50기준 # 뽑는다
a = np.random.randint(1,100,size = (2,10,10))


In [332]:
a_1 = np.where(50 >= a,1 ,2) 
a_1

array([[[1, 2, 2, 2, 1, 1, 2, 2, 1, 1],
        [1, 1, 2, 1, 1, 1, 2, 2, 2, 2],
        [2, 1, 2, 1, 1, 1, 2, 1, 2, 1],
        [2, 2, 2, 1, 1, 1, 2, 2, 1, 2],
        [2, 1, 2, 1, 2, 2, 1, 2, 1, 1],
        [2, 1, 2, 1, 2, 1, 1, 1, 2, 1],
        [1, 2, 2, 1, 2, 1, 2, 2, 2, 2],
        [1, 2, 2, 2, 2, 1, 2, 1, 2, 1],
        [1, 1, 2, 1, 2, 1, 2, 1, 2, 2],
        [2, 1, 1, 1, 2, 2, 2, 1, 1, 1]],

       [[2, 2, 2, 2, 2, 2, 1, 1, 2, 1],
        [1, 1, 2, 2, 1, 1, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 1, 2, 2],
        [1, 2, 1, 1, 2, 2, 1, 2, 1, 2],
        [1, 1, 1, 1, 2, 1, 1, 1, 2, 2],
        [1, 2, 1, 1, 2, 2, 1, 2, 2, 1],
        [1, 2, 1, 1, 2, 2, 1, 1, 1, 2],
        [1, 2, 1, 1, 1, 1, 2, 2, 2, 2],
        [2, 2, 2, 1, 2, 2, 1, 2, 1, 1],
        [2, 2, 2, 2, 2, 1, 1, 1, 2, 2]]])

In [330]:
print(a_1[1,5:10,5:10])

[[2 1 2 2 1]
 [2 1 1 1 2]
 [1 2 2 2 2]
 [2 1 2 1 1]
 [1 1 1 2 2]]


In [333]:
print(a_1[1,0:4,5:10])

[[2 1 1 2 1]
 [1 2 2 2 2]
 [2 2 1 2 2]
 [2 1 2 1 2]]
