In [1]:
words = ["school", "game", "piano", "science", "hotel","mountain"]
new_words = []
for words in words:
    if len(words) > 5:
        new_words.append(words)
print(new_words)

['school', 'science', 'mountain']


In [2]:
words = ["school", "game", "piano", "science", "hotel","mountain"]
new_words = []
for i in words:
    if len(i) > 5:
        new_words.append(i)
print(new_words)

['school', 'science', 'mountain']


In [3]:
class Dog:
    def eat(self):
        print("eat")
    def walk(self):
        print("walk")


In [4]:
choco = Dog()
choco.eat()

eat


In [5]:
jjong = Dog()
jjong.walk()

walk


In [6]:
class Dog:
    def __init__(self):
        self.hungry = 0
        self.name = "Dog"

    def eat(self):
        print("eat")
    
    def walk(self):
        print("walk")
        
    def showme(self):
        print("{}:{}".format(self.name),self.color)

In [7]:
choco = Dog()
choco.eat()

eat


In [10]:
jjong = Dog("jjong","white")
jjong = Dog()
jjong.walk()

TypeError: __init__() takes 1 positional argument but 3 were given

In [42]:
# 객체와 클래스
class Dog:
    def __init__(self, name, color):
        self.hungry = 0
        self.name = name
        self.color = color

    def eat(self):
        self.hungry -= 10
        print("밥먹음", self.hungry)
    
    def walk(self):
        self.hungry_ +=10
        print("산책",self.hungry)
        
    def showme(self):
        print("{}:{}".format(self.name,self.color))

In [43]:
jjong = Dog("jjong","white")
print(jjong.hungry)
jjong.hungry = 10
print(jjong.hungry)

0
10


In [44]:
#비공개 속성
class Dog:
    def __init__(self, name, color):
        self.__hungry = 0
        self.name = name
        self.color = color

    def eat(self):
        self.__hungry -= 10
        print("밥먹음", self.__hungry)
    
    def walk(self):
        self.__hungry +=10
        print("산책", self._hungry)
        
    def showme(self):
        print("{}:{}".format(self.name,self.color))

In [45]:
mery = Dog("mery","black")
mery.eat()
mery.walk()


밥먹음 -10


AttributeError: 'Dog' object has no attribute '_hungry'

In [39]:
class Dog:
    dog_count = 0
    
    def __init__(self,name,color):
        self.name = name
        self.color = color
        Dog.dog_count +=1
        
    def dogCount(self):
        self.dog_count +=1
        print("총 강아지는 ",Dog.dog_count)
        print("내 강아지는 ",self.dog_count)

In [40]:
hello = Dog("hello", "black")
hello.dogCount()

총 강아지는  1
내 강아지는  2


In [41]:
happy = Dog("happy","black")
happy.dogCount()

총 강아지는  2
내 강아지는  3


In [46]:
class Animal:
    def __init__(self):
        self.hungry =0
        
    def eat(self):
        self.hungry -= 10
        print("밥먹음",self.hungry)
        
    def walk(self):
        self.hungry +=10
        print("산책", self.hungry)

In [51]:
class Dog(Animal):
    def __init__(self):
        super(). __init__()
    
    def sound(self):
        print("멍멍")

In [52]:
dog = Dog()
dog.sound()

멍멍


In [61]:
for x in range(10,-10,-1):
    print(10/x)

1.0
1.1111111111111112
1.25
1.4285714285714286
1.6666666666666667
2.0
2.5
3.3333333333333335
5.0
10.0


ZeroDivisionError: division by zero

In [63]:
x = [1,2,3]

try:
    a= x[4]
except Exception as e:
    print("error:", e)

error: list index out of range


In [2]:
import pickle

try:
    with open("data3.plk","rb") as file:
        name = pickle.load(file)
        address = pickle.load(file)
        email = pockle.load(file)
        print(name,address,email)

except FileNotFoundError as e:
    print("file이 존재하지 않습니다.")
    name = input("이름을 입력해주세요")
    address = input("주소를 입력해주세요")
    email = input("이메일을 입력해주세요")
    
    with open("dat3.plk","wb") as file:
        pickle.dump(name,file)
        pickle.dump(address,file)
        pickle.dump(email,file)
        
    print("파일이 생성되었습니다.")
    

file이 존재하지 않습니다.
이름을 입력해주세요호빵맨
주소를 입력해주세요충무로
이메일을 입력해주세요jfj@ada.com
파일이 생성되었습니다.


In [1]:
import calc
print(calc.add(5,6))

ModuleNotFoundError: No module named 'calc'

In [2]:
from calc import add, sub

print(add(5,6))

11


In [1]:
import pkcalc.calc as calc
print(calc.name)

clac


In [1]:
from pkcalc.calc import add, sub

clac package


In [3]:
import sys
print(sys.path)

['C:\\Users\\691\\kdigital', 'C:\\Users\\691\\anaconda3\\python38.zip', 'C:\\Users\\691\\anaconda3\\DLLs', 'C:\\Users\\691\\anaconda3\\lib', 'C:\\Users\\691\\anaconda3', '', 'C:\\Users\\691\\anaconda3\\lib\\site-packages', 'C:\\Users\\691\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\691\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\691\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\691\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\691\\.ipython']


In [1]:
print("clac package")
from ,calc import add, sub

SyntaxError: invalid syntax (<ipython-input-1-51be26d01bcf>, line 2)

In [3]:
import numpy as np

In [4]:
import pandas as pd

In [9]:
def gugudan(num):
    for i in range(1,10):
        print("{} * {} = {}".format(num, i , num * i))

In [10]:
gugudan(3)

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27


In [8]:
matrix_1 = [[1,2],[3,4]]
matrix_2 = [[5,6],[7,8]]

In [13]:
#matrix 원소의 힘
c = []
for i in range(len(matrix_1)):
    temp = []
    for j in range(len(matrix_2)):
        temp.append(matrix_1[i][j]+matrix_2[i][j])
    c.append(temp)
print(c)

[[6, 8], [10, 12]]


In [40]:
for i in matrix_1:
    for j in matirx_1:
         matrix_1[i][j] +=1
    print(matrix_1)

NameError: name 'matirx_1' is not defined

In [41]:
matrix_3 = [[1,2],[3,4]]
matrix_4 = [[5,6],[7,8]]

In [77]:
matrix_result = []
for i in range(len(matrix_3)):
    tmp = []
    for j in range(len(matrix_4)):
        tmp.append(matrix_3[i][j]+matrix_4[i][j])
    matrix_result.append(tmp)
print(matirx_result)

[[ 6  8]
 [10 12]]


In [78]:
matirx_result = np.array(matrix_3)+np.array(matrix_4)
print(matrix_result)

[[6, 8], [10, 12]]


In [53]:
import time

In [54]:
size = 10000000
#list
x = list(range(size))
y = list(range(size))

In [55]:
start_time = time.time()
z = [x[i]+x[i] for i in range(size)]
print("리스트 걸린시간", time.time()-start_time)

리스트 걸린시간 1.8810715675354004


In [56]:
#adlist
x = np.arange(size)
y = np.arange(size)
start_time = time.time()
z = x + y
print("넘파이 걸린시간", time.time()-start_time)

넘파이 걸린시간 0.17758679389953613


In [60]:
x = np.uint(64)
print(x)
print(type(x))
print(x.dtype)

64
<class 'numpy.uint32'>
uint32


In [61]:
x = np.array([1,2,3,4])
print(x)
print(type(x))
print(x.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int32


In [66]:
x = np.float32([1,2,3,4])
print(x)
print(type(x))
print(x.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float32


In [67]:
x = np.array.32([1,2,3,4], dtype=np.float16)
print(x)
print(type(x))
print(x.dtype)

SyntaxError: invalid syntax (<ipython-input-67-d0a2d4a84014>, line 1)

In [69]:
np.issubdtype(x.dtype,np.int64)

False

In [73]:
x = np.arange(12).reshape(2,6)
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [74]:
print(x.shape)

(2, 6)
