In [1]:
0b10111

23

In [2]:
bin(23)

'0b10111'

In [3]:
0o14

12

In [4]:
oct(12)

'0o14'

In [5]:
0x23

35

In [6]:
hex(35)

'0x23'

In [7]:
True and True

True

In [8]:
True and False

False

In [9]:
True or False

True

In [10]:
not True

False

In [11]:
i = 5
i > 10 and i < 5

False

In [12]:
i = 5
i > 10 or i < 5

False

In [13]:
 i == 5

True

In [14]:
i <= 5

True

In [18]:
a = (1,2,3) #튜플 변경 불가
b = [2,3,4] #리스트

In [19]:
c = {3,4,5} #셋 집합

In [22]:
e = [4,5,6]

In [32]:
c+e # 타입 에러, 규칙에 맞지않다. 둘 중 하나의 타입을 변경

TypeError: unsupported operand type(s) for +: 'set' and 'list'

In [33]:
z=set(e) # set은 집합으로 변경시켜준다.
z

{4, 5, 6}

In [34]:
z =tuple(z) # tuple로 변경
z

(4, 5, 6)

In [35]:
z = list(z) #list로 변경
z

[4, 5, 6]

In [29]:
c-set(e) #차집합

{3}

In [30]:
c & set(e) #교집합

{4, 5}

In [31]:
c | set(e) #합집합

{3, 4, 5, 6}

In [20]:
d = {"a":1, "b":2} #딕셔너리

In [36]:
d.keys

<function dict.keys>

In [37]:
d.keys() # 내용을 볼 수 있음

dict_keys(['a', 'b'])

In [39]:
d.values()

dict_values([1, 2])

In [40]:
d.items() #리스트 안에 삽입 가능

dict_items([('a', 1), ('b', 2)])

In [21]:
print("a"+"b")

ab


In [23]:
b.append(e) # 덩어리가 들어간다.


In [24]:
b

[2, 3, 4, [4, 5, 6]]

In [25]:
b[3]

[4, 5, 6]

In [26]:
b.extend(e) #하나씩 들어간다.
b

[2, 3, 4, [4, 5, 6], 4, 5, 6]

In [27]:
b.insert(2,e)
b

[2, 3, [4, 5, 6], 4, [4, 5, 6], 4, 5, 6]

### 암호화, 복화화

In [ ]:
문제
시저가 "20210202 venice attack" -> 클레오파트라 전송
시저암호
시저는 암호화
클레오파트라는 복화화

In [ ]:
chr = 문자
ord = 숫자

In [3]:
secret= "20210202 venice attack" 
secret1= "" 

for i in secret: 
    s=ord(i) 
    s=s+3 
    ii=chr(s) 
    secret1=secret1+ii
    
print(secret1)

53543535#yhqlfh#dwwdfn


In [4]:
secret2 = ""
for i in secret1:
    s=ord(i)
    s=s-3
    ii=chr(s)
    secret2=secret2+ii

print(secret2)
    

20210202 venice attack


In [1]:
# a = "20210202 venice attack"
# # secret= "20210202 venice attack" 
# secret1= ""
# def change(a):
#     for i in secret: 
#         print(chr(ord(i)+3)) 
# #         s=s+3 
# #         ii=chr(s) 
# # #         secret1=secret1+ii
#     return secret1
# change(a)

NameError: name 'secret' is not defined

In [68]:
a = "20210202 venice attack"
b= ""
c = []
def change(a):
    for i in a: 
        print(chr(ord(i)+3))
#     c.append(change(a))
    return b
change(a)
# print(c)

5
3
5
4
3
5
3
5
#
y
h
q
l
f
h
#
d
w
w
d
f
n


''

In [96]:
a = "20210202 venice attack"
# b= ""
c = []
def change(a):
    for i in a: 
        c.append(chr(ord(i)+3))
    return c
change(a)
print(c)

['5', '3', '5', '4', '3', '5', '3', '5', '#', 'y', 'h', 'q', 'l', 'f', 'h', '#', 'd', 'w', 'w', 'd', 'f', 'n']


In [99]:
b = []
def change_1(c):
    for i in c:
        b.append(chr(ord(i)-3))
    return b

change_1(c)
print(b)

['2', '0', '2', '1', '0', '2', '0', '2', ' ', 'v', 'e', 'n', 'i', 'c', 'e', ' ', 'a', 't', 't', 'a', 'c', 'k']


### 3,6,9 실습
   - 3,6,9 마다 '짝' 넣기

In [128]:
x = [1,2,3,4,5,6,7,8,9,10]

In [143]:
for i in x:
    if i % 3 == 0:
        print("짝")

    else:
        print(i)

1
2
짝
4
5
짝
7
8
짝
10


### ktx
  - 1칸에 한명씩 앉히기

In [2]:
import numpy as np

In [196]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [264]:
i = 26
ktx = np.zeros((4,int(i/2)),dtype=object)
ktx

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [214]:
ord("a")

97

In [3]:
i = 26
ktx1 = np.zeros((4,int(i/2)))
ktx1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
for i in range(65,91):
#     print(chr(ord("a")+i))
# print(i)
    print(chr(i))
    ktx1=np.append([0],[i])
ktx1

A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z


array([ 0, 90])

In [227]:
ktx[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [232]:
print(chr(ord("a")+1))

b


In [222]:
al = chr(ord("i")+1)
al

'j'

In [268]:
for i in range(len(ktx[0])):
    x=[0,3]
    for j in x:
        ktx[j][i] = chr(65+2*i+x.index(j))
ktx

array([['A', 'C', 'E', 'G', 'I', 'K', 'M', 'O', 'Q', 'S', 'U', 'W', 'Y'],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ['B', 'D', 'F', 'H', 'J', 'L', 'N', 'P', 'R', 'T', 'V', 'X', 'Z']],
      dtype=object)

In [224]:
for i in al: 
    print(chr(ord(i)+1))

k


### 3,6,9 심화

In [39]:
for i in range(1,101):
    if i in [3,6,9]:
        print("짝")
    elif str([i]).split([1])
        print("짝")
    else:
        print(i)

SyntaxError: invalid syntax (<ipython-input-39-c94e55e81371>, line 4)

In [44]:
for i in range(1,101):
    if str(i).split():
        print("짝")
    else:
        print(i)


짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
짝
