In [1]:
matrix_1 = [[1,2],[3,4]]
matrix_2 = [[5,6],[7,8]]

In [8]:
for i in range(len(matrix_1)):
    temp = []
    for j in range(len(matrix_2)):
        temp.append(matrix_1[i][j]+matrix_2[i][j])
    print(temp)

[6, 8]
[10, 12]


### NUMPY

In [2]:
import numpy as np

In [4]:
matrix_3 = np.array(matrix_1)+ np.array(matrix_2)
print(matrix_3)

[[ 6  8]
 [10 12]]


In [10]:
matrix_1 = [[1,2],[3,4]]

In [11]:
for i in range(len(matrix_1)):
    for j in range(len(matrix_2)):
        matrix_1[i][j] = matrix_1[i][j] +1

print(matrix_1)

[[2, 3], [4, 5]]


In [20]:
x_list = [1,2,3]
y_list = ["a","b","c"]
z_list = ["A","B","C"]

In [24]:
for i in x_list:
    for j in y_list:
        for k in z_list:
            print(i,j,k)

1 a A
1 a B
1 a C
1 b A
1 b B
1 b C
1 c A
1 c B
1 c C
2 a A
2 a B
2 a C
2 b A
2 b B
2 b C
2 c A
2 c B
2 c C
3 a A
3 a B
3 a C
3 b A
3 b B
3 b C
3 c A
3 c B
3 c C


In [31]:
c = [[1,2,3],[1,2,3]]

In [34]:
len(c)

2

In [39]:
range(len(c))

range(0, 2)

In [35]:
d = ["학교","충무로"]

In [38]:
range(len(d))

range(0, 2)

In [40]:
e = [1,2,3]

In [41]:
range(len(e))

range(0, 3)

In [42]:
import  time

In [43]:
size = 10000000

In [45]:
x = list(range(size))
y = list(range(size))

In [48]:
start_time = time.time()
z = [x[i]+x[i] for i in range(size)]
print("리스트 걸린 시간",time.time()-start_time)

리스트 걸린 시간 1.4161765575408936


In [49]:
a = np.arange(size)
b = np.arange(size)

In [50]:
start_time = time.time()
z = a + b
print("넘파이 걸린시간", time.time()-start_time)

넘파이 걸린시간 0.13463902473449707


In [53]:
x = np.array([1,2,3,4])

In [55]:
print(x.dtype)

int32


### 다차원 ndarray

In [57]:
# 0 차원
np.array(1)

array(1)

In [58]:
# 1차원
np.array([1,2])

array([1, 2])

In [59]:
#2차원 이상
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
x = np.array(1)
print(x.shape) #행렬구조
print(x.ndim) #차원
print(x.size) #원소의 개수

()
0
1


In [7]:
y = np.array([1,2])
print(y.shape) #행렬구조
print(y.ndim) #차원
print(y.size) #원소의 개수

(2,)
1
2


In [6]:
z = np.array([[1,2,3],[4,5,6]])
print(z.shape) #행렬구조
print(z.ndim) #차원
print(z.size) #원소개수

(2, 3)
2
6


### arange

In [8]:
#파이썬 range와 비슷

In [12]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
x = np.arange(10.0)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [15]:
x = np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [16]:
x = np.arange(1,10,0.5)
print(x)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [17]:
x = np.arange(10,1,-0.5)
print(x)

[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


### linspace

In [18]:
x = np.linspace(1,20,5)
print(x)

[ 1.    5.75 10.5  15.25 20.  ]


In [20]:
x = np.linspace(1,20,10,endpoint=False)
print(x)

[ 1.   2.9  4.8  6.7  8.6 10.5 12.4 14.3 16.2 18.1]


### reshape

In [23]:
np.array([[1,2],[3,4],[5,6]]).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.array([[1,2],[3,4],[5,6]]).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
x = np.arange(9).reshape(3,3)
print(x) # 2차원

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
x = np.arange(24).reshape(2,3,4)
print(x) #3차원

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [27]:
x = np.arange(24).reshape(2,4,3)
print(x) #3차원

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [28]:
x = np.arange(16).reshape(2,2,2,2)
print(x) #4차원

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [33]:
x = np.array([[1,2],[3,4],[5,6]])
print(x)
print(x.reshape(2,3)) #데이터를 유지하고 형태변경

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [34]:
x = np.arange(9).reshape(3,-1)
print(x) #개수에 맞춰 생성

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### slicing

In [37]:
# 1차원 슬라이싱
x = np.arange(20)
print(x)
print(x[1:3])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2]


In [40]:
#2차원 슬라이싱
x = np.arange(20).reshape(4,5)
print(x)
# print(x[1:3])
# print(x[1:3,1:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [41]:
#2차원 슬라이싱
x = np.arange(20).reshape(4,5)
# print(x)
print(x[1:3])
# print(x[1:3,1:3])

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [42]:
#2차원 슬라이싱
x = np.arange(20).reshape(4,5)
# print(x)
# print(x[1:3])
print(x[1:3,1:3])

[[ 6  7]
 [11 12]]


In [43]:
#3차원 슬라이싱
x = np.arange(30).reshape(2,5,3)
print(x)
# print(x[:,3:5,1])0

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [44]:
#3차원 슬라이싱
x = np.arange(30).reshape(2,5,3)
# print(x)
print(x[:,3:5,1])

[[10 13]
 [25 28]]


In [45]:
#3차원 슬라이싱
x = np.arange(30).reshape(2,5,3)
# print(x)
print(x[:3, :3, :3])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]]]


In [50]:
#3차원 슬라이싱
x = np.arange(30).reshape(2,5,3)
# print(x)
print(x[:3, :1])

[[[ 0  1  2]]

 [[15 16 17]]]


### 실습1

In [2]:
x = [1,2,3,4,5,6,7,8,9]
y = [10,20,30,40,50,60,70,80,90]

In [6]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
y = np.arange(10,100,10).reshape(3,3)
y

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [8]:
x+y

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [10]:
x.dot(y)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [12]:
np.cumprod([x,y]) # 모르겠음

array([          1,           2,           6,          24,         120,
               720,        5040,       40320,      362880,     3628800,
          72576000, -2117687296,  1191854080,  -536838144, -2145517568,
         137625600, -1874853888, -1233125376], dtype=int32)

### 실습2

In [27]:
z = np.linspace(1,20,30)
z

array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

In [28]:
z+10

array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

In [4]:
a = np.random.randint(1,100,size=(2,10,10))
a

array([[[19, 38, 59,  1, 15, 45, 41, 38, 55, 35],
        [27, 44, 62, 22, 35, 86, 92, 99, 83, 94],
        [11, 32, 95, 74, 70, 10, 51, 20, 11, 68],
        [85, 65, 67, 20, 50, 28, 52, 22, 14, 95],
        [15, 91,  9, 18, 72, 97, 99, 33, 88, 28],
        [49,  1,  2, 84, 96, 56,  3, 12, 94, 66],
        [62, 36, 85, 14, 83, 53, 73, 84, 24, 79],
        [93, 20, 97, 79, 83, 22, 92, 36, 56, 12],
        [27, 41, 19, 91, 55,  7, 90, 32, 60, 19],
        [ 7, 83, 81, 74, 43,  6, 82, 75, 73, 71]],

       [[ 3, 39, 60,  6, 86, 73, 14, 31,  4, 71],
        [61, 42,  1, 36, 74, 66, 31, 19, 20, 90],
        [59, 20,  4, 88, 78, 55, 49, 42, 63,  2],
        [81,  4, 52, 19, 41, 24,  2, 18, 57, 42],
        [95,  8,  2, 11, 63, 38, 12, 34, 84, 22],
        [72, 65, 77, 38, 76, 13, 14, 58, 54, 64],
        [ 5, 51, 10, 46, 76, 68, 26, 78, 44, 26],
        [91, 15, 20, 66, 10, 29, 62, 83, 10, 20],
        [ 5, 95, 16, 98, 51, 18, 33, 97, 38, 60],
        [89, 94, 74, 61,  9, 55, 41, 77, 34, 67]

In [5]:
y = np.where(a >= 50,1,2)
y

array([[[2, 2, 1, 2, 2, 2, 2, 2, 1, 2],
        [2, 2, 1, 2, 2, 1, 1, 1, 1, 1],
        [2, 2, 1, 1, 1, 2, 1, 2, 2, 1],
        [1, 1, 1, 2, 1, 2, 1, 2, 2, 1],
        [2, 1, 2, 2, 1, 1, 1, 2, 1, 2],
        [2, 2, 2, 1, 1, 1, 2, 2, 1, 1],
        [1, 2, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 2, 1, 2, 1, 2],
        [2, 2, 2, 1, 1, 2, 1, 2, 1, 2],
        [2, 1, 1, 1, 2, 2, 1, 1, 1, 1]],

       [[2, 2, 1, 2, 1, 1, 2, 2, 2, 1],
        [1, 2, 2, 2, 1, 1, 2, 2, 2, 1],
        [1, 2, 2, 1, 1, 1, 2, 2, 1, 2],
        [1, 2, 1, 2, 2, 2, 2, 2, 1, 2],
        [1, 2, 2, 2, 1, 2, 2, 2, 1, 2],
        [1, 1, 1, 2, 1, 2, 2, 1, 1, 1],
        [2, 1, 2, 2, 1, 1, 2, 1, 2, 2],
        [1, 2, 2, 1, 2, 2, 1, 1, 2, 2],
        [2, 1, 2, 1, 1, 2, 2, 1, 2, 1],
        [1, 1, 1, 1, 2, 1, 2, 1, 2, 1]]])

In [6]:
y[1:,5:11,5:11]

array([[[2, 2, 1, 1, 1],
        [1, 2, 1, 2, 2],
        [2, 1, 1, 2, 2],
        [2, 2, 1, 2, 1],
        [1, 2, 1, 2, 1]]])