# NUMPY

In [1]:
import numpy as np
import pandas as pd

In [6]:
x = np.random.randint(1,101,size = (2,10,10))

In [7]:
x

array([[[ 50,  99,  27,  28,  13,  69,  16,  98,  45,   6],
        [ 56,  81,  47,  75,  79,  74,  59,  87,   1,  50],
        [ 21,  55,  70,  29,  41,  16,  79,   5,  54,   2],
        [ 56,  19,  31,  49,  43,   5,  78,  59,  74,  18],
        [ 55,  53,  73,  14,  27,  47,  19,   4,  16,  78],
        [ 21,  91,  55,  59,  60,  32,  73,  46,  47,   6],
        [ 75,  20,  60,  80,  32,  73,  54,  55,  69,  20],
        [  7,  75,  82,  71,  90,  54,   6,  34,   9,  75],
        [  1,   3,  75,  43,  83,  28,  66,  16,  96,  10],
        [ 88,  70,  67,  18,  30,  89,  87,  67,  35,  51]],

       [[ 47,  60,  56,   8,  45,   8,  46,  72,  78,  91],
        [ 70,  82,   2,  94,  39,   4,  30,  45,  38,   9],
        [ 65,  35,  56,  59,  30,  31,  25,  44,  94,   5],
        [ 99,  91,  69,  58,  82,  77,  44,  76,  13,  99],
        [ 37,  21,  76,  98,  73,  51,  50,   1,  20,  48],
        [ 71,  19,  70,  46, 100,  29,  12,  96,  36,  66],
        [ 38,  93,  98,  49,  38,   4,

In [15]:
y = np.where(x >= 50,1,2)
y

array([[[1, 1, 2, 2, 2, 1, 2, 1, 2, 2],
        [1, 1, 2, 1, 1, 1, 1, 1, 2, 1],
        [2, 1, 1, 2, 2, 2, 1, 2, 1, 2],
        [1, 2, 2, 2, 2, 2, 1, 1, 1, 2],
        [1, 1, 1, 2, 2, 2, 2, 2, 2, 1],
        [2, 1, 1, 1, 1, 2, 1, 2, 2, 2],
        [1, 2, 1, 1, 2, 1, 1, 1, 1, 2],
        [2, 1, 1, 1, 1, 1, 2, 2, 2, 1],
        [2, 2, 1, 2, 1, 2, 1, 2, 1, 2],
        [1, 1, 1, 2, 2, 1, 1, 1, 2, 1]],

       [[2, 1, 1, 2, 2, 2, 2, 1, 1, 1],
        [1, 1, 2, 1, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 2, 2, 2, 2, 1, 2],
        [1, 1, 1, 1, 1, 1, 2, 1, 2, 1],
        [2, 2, 1, 1, 1, 1, 1, 2, 2, 2],
        [1, 2, 1, 2, 1, 2, 2, 1, 2, 1],
        [2, 1, 1, 2, 2, 2, 2, 2, 1, 1],
        [2, 1, 1, 1, 2, 1, 1, 1, 2, 1],
        [1, 1, 2, 2, 2, 2, 1, 2, 1, 2],
        [1, 2, 2, 1, 2, 1, 1, 1, 1, 1]]])

In [20]:
y[:2,5:11]

array([[[2, 1, 1, 1, 1, 2, 1, 2, 2, 2],
        [1, 2, 1, 1, 2, 1, 1, 1, 1, 2],
        [2, 1, 1, 1, 1, 1, 2, 2, 2, 1],
        [2, 2, 1, 2, 1, 2, 1, 2, 1, 2],
        [1, 1, 1, 2, 2, 1, 1, 1, 2, 1]],

       [[1, 2, 1, 2, 1, 2, 2, 1, 2, 1],
        [2, 1, 1, 2, 2, 2, 2, 2, 1, 1],
        [2, 1, 1, 1, 2, 1, 1, 1, 2, 1],
        [1, 1, 2, 2, 2, 2, 1, 2, 1, 2],
        [1, 2, 2, 1, 2, 1, 1, 1, 1, 1]]])

In [28]:
y[1:,5:11]

array([[[1, 2, 1, 2, 1, 2, 2, 1, 2, 1],
        [2, 1, 1, 2, 2, 2, 2, 2, 1, 1],
        [2, 1, 1, 1, 2, 1, 1, 1, 2, 1],
        [1, 1, 2, 2, 2, 2, 1, 2, 1, 2],
        [1, 2, 2, 1, 2, 1, 1, 1, 1, 1]]])

# Pandas

### Series

In [36]:
y[1:,5:11,0]

array([[1, 2, 2, 1, 1]])

In [31]:
y[1:,5:11,1]

array([[2, 1, 1, 1, 2]])

In [32]:
y[1:,5:11,2]

array([[1, 1, 1, 2, 2]])

In [33]:
y[1:,5:11,4]

array([[1, 2, 2, 2, 2]])

In [35]:
y[1:,5:11,5:11]

array([[[2, 2, 1, 2, 1],
        [2, 2, 2, 1, 1],
        [1, 1, 1, 2, 1],
        [2, 1, 2, 1, 2],
        [1, 1, 1, 1, 1]]])

In [37]:
x = [1,2,3,4,5]

In [39]:
pd.Series(x)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [42]:
y = np.array([1,2,3,4,5])

In [43]:
pd.Series(y)

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [44]:
x[0]

1

In [47]:
x[1:3]

[2, 3]

In [48]:
x[::-1]

[5, 4, 3, 2, 1]

In [54]:
x[:-1]

[1, 2, 3, 4]

In [56]:
y[y>3]

array([4, 5])

In [58]:
y+1

array([2, 3, 4, 5, 6])

In [60]:
y*10

array([10, 20, 30, 40, 50])

In [62]:
y+y

array([ 2,  4,  6,  8, 10])

### Series Index
   - 기본적으로 index와 value로 값이 구분되어 있다.

In [63]:
x = [1,2,3,4,5]
x = pd.Series(x)

In [64]:
print(x.index)
print(x.values)

RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]


In [65]:
#인덱스명을 변경할 수 있다.

In [66]:
x = [1,2,3,4,5]
x = pd.Series(x, index=["a","b","c","d","e"])

In [68]:
print(x["a"]) # 명시적 인덱스접근

1


In [69]:
print(x[0]) # 묵시적 인덱스 접근

1


In [70]:
print(x[["a","e"]]) #팬시색인, 한번에 여러값 접근

a    1
e    5
dtype: int64


In [71]:
print(x.a)# 또다른 접근방법

1


### 딕셔너리 to Series
   - 딕셔너리를 사룡하여 Series를 만들면 key값을 index로 사용한다.

In [72]:
x = {"수학":90, "영어":80, "과학":95, "미술":80}

In [73]:
x = pd.Series(x)
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [74]:
x["수학"]

90

In [77]:
#슬라이싱 가능
x["영어":]

영어    80
과학    95
미술    80
dtype: int64

In [78]:
# 인덱스 값을 지정하여 일부값만 Series로 생성

In [81]:
x = pd.Series(x, index = ["수학","영어","과학"])
x

수학    90
영어    80
과학    95
dtype: int64

### Multi Index
   - 인덱스를 여러개 가질 수 있다

In [84]:
student_1 = {"수학":90, "영어":80, "과학":95, "미술":80}
student_2 = {"수학":70, "영어":80, "과학":100, "미술":70}

In [86]:
#index_1 = [홍길동",홍길동",홍길동",홍길동","이몽룡",이몽룡",이몽룡",이몽룡"]
index_1 = ["홍길동" for i in range(len(student_1))]+["이몽룡"for i in range(len(student_2))]

In [87]:
#index_2 = ["수학","영어","과학","미술",수학","영어","과학","미술"]
index_2 = [i for i in student_1]+[i for i in student_2]

In [88]:
value_all = list(student_1.values())+list(student_2.values())

In [90]:
students = pd.Series(value_all, index = [index_1, index_2])

In [91]:
students

홍길동  수학     90
     영어     80
     과학     95
     미술     80
이몽룡  수학     70
     영어     80
     과학    100
     미술     70
dtype: int64

### 결측값 처리 방법 (NaN, None)
   - 비어있는 값들에 대한 처리

In [92]:
x = [1, None, 2, None, 3,4, None]
x = pd.Series(x)

In [93]:
#결측값 무시하고 계산
print(x.sum()) #10
print(x.max()) #4
print(x.min()) #1

10.0
4.0
1.0


In [94]:
#결측값 개수
print(x.isnull().sum()) #3
print(x.notnull().sum()) #4

3
4


In [96]:
#결측값 제거
x.dropna()


0    1.0
2    2.0
4    3.0
5    4.0
dtype: float64

In [97]:
#결측값을 다른 값으로 채우기
x.fillna(0)

0    1.0
1    0.0
2    2.0
3    0.0
4    3.0
5    4.0
6    0.0
dtype: float64

### concat
  - 데이터 연결, numpy, concatenate 기능

In [98]:
x = pd.Series([1,2,3])
y = pd.Series([4,5,6])
z = pd.Series([7,8,9])

In [99]:
pd.concat([x,y,z])

0    1
1    2
2    3
0    4
1    5
2    6
0    7
1    8
2    9
dtype: int64

In [102]:
#같은 인덱스번호가 있을 경우 오류
pd.concat([x,y,z], verify_integrity=True)

ValueError: Indexes have overlapping values: Int64Index([0, 1, 2], dtype='int64')

In [105]:
# 합치면서 인덱스 번호 다시 정리
pd.concat([x,y,z],ignore_index=True)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [106]:
# 축변경
pd.concat([x,y,z], ignore_index=True, axis=1)

0  1  2
0  1  4  7
1  2  5  8
2  3  6  9

In [107]:
x = pd.Series([1,2,3,4])
y = pd.Series([4,5,6])
z = pd.Series([7,8,9])

In [108]:
#개수가 맞지 않을 경우 교집합
pd.concat([x,y,z],ignore_index=True, axis = 1,join="inner")

0  1  2
0  1  4  7
1  2  5  8
2  3  6  9

In [110]:
# 개수가 맞지 않을경우 합집합
pd.concat([x,y,z], ignore_index=True, axis = 1, join="outer")

0    1    2
0  1  4.0  7.0
1  2  5.0  8.0
2  3  6.0  9.0
3  4  NaN  NaN